Segunda parte ejercicios
Profe que pena no me deja subir los ejercicios como los anteriores, me dice que hay un error
To https://github.com/gforero31934/Actividad1_DesarroSoftware.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/gforero31934/Actividad1_DesarroSoftware.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.